# Generated by Django 5.2.8 on 2025-11-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
