# Generated by Django 5.2.8 on 2025-11-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_inventory', '0002_alter_employee_hire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tracks_software',
            field=models.BooleanField(default=False, help_text='Indicates if items in this category require software tracking.'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specs', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('IN_USE', 'in use'), ('MAINTENANCE', 'maintenance'), ('DISCARDED', 'discarded')], default='AVAILABLE ', max_length=20)),
                ('bought_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bought_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_inventory.category')),
                ('person_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nexus_inventory.employee')),
                ('installed_software', models.ManyToManyField(blank=True, to='nexus_inventory.software')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
