# Generated by Django 5.2.8 on 2026-03-03 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_inventory', '0003_software_category_tracks_software_asset_delete_item'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_image', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_history', to='nexus_inventory.asset'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tracks_software',
            field=models.BooleanField(default=False),
        ),
    ]
