# Generated by Django 5.2.8 on 2025-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_inventory', '0003_software_category_tracks_software_asset_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_history',
            field=models.ManyToManyField(blank=True, to='nexus_inventory.assethistory'),
        ),
    ]
