# Generated by Django 5.2.8 on 2026-02-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_inventory', '0005_asset_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='tracks_software',
            field=models.BooleanField(default=False),
        ),
    ]
