# Generated by Django 5.2.8 on 2026-02-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_inventory', '0006_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
    ]
